on:
  workflow_dispatch:
    inputs:
      context:
        description: 'What does this deployment do?'
        type: string
        required: true
name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
jobs:
  deploy:
    name: Deploy Preview to Vercel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Announce deployment context
        run: "echo Context: ${{ inputs.context }}"
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > deployment-url.txt 2> deployment-error.txt
      - name: Link deployment URL to custom domain
        run: vercel alias $(cat deployment-url.txt | head -1) vercel.caparas.cloud --token=${{ secrets.VERCEL_TOKEN }}
