on:
  workflow_dispatch:

name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  DEFAULT_REF: refs/heads/${{ github.event.repository.default_branch }}

jobs:
  deploy:
    name: Deploy Preview to Vercel
    environment: Staging
    runs-on: ubuntu-latest
    steps:
      - name: Branch sense checks
        run: |
          if [ ${{ env.DEFAULT_REF }} == ${{ github.ref }}  ]; then
            echo "Can't run this workflow on the main branch."
            exit 1
          fi
      - name: Configuration variable sense checks
        run: |
          if [ -z "${{ vars.PREVIEW_DOMAIN }}" ] || [ -z "${{ secrets.VERCEL_TOKEN }}" ]; then
            echo "Ensure that all required configuration variables are defined."
            exit 1
          fi
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=Preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > deployment-url.txt 2> deployment-error.txt
      - name: Link deployment URL to custom domain
        run: vercel alias $(cat deployment-url.txt | head -1) ${{ vars.PREVIEW_DOMAIN }} --token=${{ secrets.VERCEL_TOKEN }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            ./.next
            ./deployment-url.txt
            ./deployment-error.txt
          retention-days: 1
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: build-artifacts
      - name: List artifacts
        run: ls -R
