on:
  pull_request:
    branches:
      - main
name: Sonarcloud Static Code Analysis
jobs:
  scan:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'CI')
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: yarn
    - name: Lint for any errors
      run: yarn lint
    - name: Build project
      run: yarn build
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
