on:
  push:
    branches-ignore:
      - main
  pull_request:
      types: [opened, synchronize, reopened]
name: Vercel Static Code Analysis
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Install dependencies mate
      run: yarn
    - name: Lint for any errors
      run: yarn lint
    - name: Build project
      run: yarn build
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
